// This file was autogenerated by gulp-closure-deps plugin.
// Please do not edit.
goog.addDependency('../test/fixtures/a.js', ['a'], [], false);
goog.addDependency('../test/fixtures/b.js', ['b'], ['a'], false);
goog.addDependency('../test/fixtures/module.js', ['module'], ['module_dep'], true);
goog.addDependency('../test/fixtures/module_dep.js', ['module_dep'], [], true);